import { Button } from "@/components/Button";
import { div } from "framer-motion/client";
import React from "react";

const filterOptions = [
  "2024collection",
  "coffeeTable",
  "glass",
  "modern",
  "minimalist",
  "sectionalSofa",
  "luxury",
  "leather",
  "diningTable",
  "marble",
  "tvStand",
  "oak",
  "storage",
  "armchair",
  "velvet",
  "patioSet",
  "outdoor",
  "rattan",
  "weather-resistant",
  "bookshelf",
  "contemporary",
  "floorLamp",
  "lighting",
  "brass",
  "consoleTable",
  "wood",
  "walnut",
  "bedsideTable",
  "reclaimedWood",
  "farmhouse",
  "loungeChair",
  "midCentury",
  "wallShelf",
  "ottoman",
  "tufted",
  "extendable",
  "chaiseLounge",
  "barStool",
  "chrome",
  "dresser",
  "solidWood",
  "bedFrame",
  "metal",
  "industrial",
  "living room",
  "seating",
  "vanity",
  "desk",
  "home office",
  "solid wood",
  "geometric",
  "plush",
  "convertible",
  "sofa",
  "queen-sized",
  "guest room",
  "natural",
  "indoor",
  "wall-mounted",
  "compartments",
  "classic",
  "wooden",
  "rocking chair",
  "ergonomic",
  "display",
  "cabinet",
  "LED lighting",
  "desk chair",
  "lumbar support",
  "executive",
  "woven",
  "jute",
  "rug",
  "corner",
  "space-saving",
  "five tiers",
  "console table",
  "glass-top",
  "metal legs",
  "lounge chair",
  "reclining",
  "loveseat",
  "USB ports",
  "coffee table",
  "rustic",
  "folding",
  "dining table",
  "expandable",
  "small spaces",
  "swivel",
  "office chair",
  "mesh",
  "adjustable armrests",
  "TV stand",
  "mid-century modern",
  "sleeper sofa",
  "area rug",
  "wool",
  "warmth",
  "console cabinet",
  "sliding doors",
  "brass accents",
  "dining set",
  "upholstered",
  "bench",
  "button-tufted",
  "footrest",
  "bamboo",
  "side table",
  "sustainable",
  "recliner",
  "comfortable",
  "king bed",
  "luxurious",
  "high headboard",
  "round",
  "pedestal base",
  "fabric",
  "cozy",
  "supportive",
  "ladder",
  "shelf",
  "compact",
  "chaise",
  "sectional sofa",
  "wide seats",
  "accent table",
  "gold metal",
  "decorative",
];

type Props = { closeMenu: () => void, handleTagClick: (tag: string) => void };

export function FilterMenu({ closeMenu, handleTagClick }: Props) {
  return (
    <>
      <div
        className="w-screen h-screen inset-0 fixed z-10"
        onClick={closeMenu}
      ></div>
      <div className="top-[48px] px-10 shadow-md rounded-b-md absolute h-[500px] justify-center overflow-scroll overflow-x-hidden flex flex-wrap gap-2 p-2 text-sm w-[500px] z-10 bg-[#f5f5f5]">
        {filterOptions.map((option, index) => (
          <Button
            key={index}
            onClick={() => handleTagClick(option)}
            className="px-2 py-1 rounded-full w-fit text-sm"
          >
            {option}
          </Button>
        ))}
      </div>
    </>
  );
}
